name: test upload

on:
  schedule:
    - cron: '*/2 * * * *'  # Menjalankan commit otomatis setiap 2 menit
  push:
    branches:
      - main  # Ubah dengan nama cabang yang sesuai jika diperlukan

jobs:
  add-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "rainmc01"
          git config --global user.email "rainmc01@users.noreply.github.com"

      - name: Add current date and time to file.txt in WIB
        run: |
          mkdir ./update
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M')
          echo "$(TZ='Asia/Jakarta' date)" > ./update/$TIMESTAMP.txt
          echo "$(TZ='Asia/Jakarta' date)" >> file.txt
          echo "Last update: $(TZ='Asia/Jakarta' date) by MyDapitt" > README.md
          git add *  # Menambahkan yang telah dimodifikasi

      - name: Commit changes
        run: |
          TS=$(date +"%Y-%m-%d_%H-%M-%S")
          git commit -m $TS
          git push

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GHT_TOKEN }}  # Token akses GitHub otomatis
        run: git push
